### ISSUE TITLE
pop_roi_connect error in snippets analysis

### ISSUE THREAD

**Issue by sato16** [sccn/roiconnect#87]
Dear roiconnect developer,

I am trying to perform snippets analysis to analyse some conditions of different data lengths. I used the following code to analyse 30-second epoch * n trials data using snippets, but encountered an error:

## Code:
```
EEG = pop_roi_connect(EEG, 'methods', measures, 'snippet', 'on', 'snip_length', 30, 'fcsave_format', 'mean_snips');
```

## Error:
```
- Error in roi_mim2_v2 (line 29)
        caainvsqrt(:, :, ifq) = sqrtm(caainv(:, :, ifq));  
- Error in data2sctrgcmim (line 238)
          [MIC(:, iind) , MIM(:, iind)] =  roi_mim2_v2(cCOH(subset, subset, :), subinds{1}, subinds{2});  
- Error in roi_connect (line 117)
            conn_mult = data2sctrgcmim(source_roi_data, EEG.roi.pnts, g.morder, 0, g.naccu, [], inds, tmpMethods1, [], 'freqresolution', g.freqresolution);  
- Error in pop_roi_connect (line 281)
    parfor isnip = 1:nsnips
```

## reproducing script for the error: 
I made a script to reproduce the error with sample data. This script works in test_pips folder
[test_30secEpochs_pipeline_connectivity_snippets.mlx.zip](https://github.com/user-attachments/files/16042656/test_30secEpochs_pipeline_connectivity_snippets.mlx.zip)

Could you please advise on how to resolve this issue? Any help would be greatly appreciated.
Thank you in advance.

Fumiaki

**Comment by nguyen-td** [comment]
Hi Fumiaki,

As always, thanks a lot for contributing! 

Unfortunately, I don't have a lot of time right now to thoroughly investigate this issue but here are a few things:
- [This](https://github.com/sccn/roiconnect/blob/master/test_pipes/test_snippets_connectivity.m) is a working script where connectivity are computed using snippets
- You should be able to debug the code yourself if you replace `parfor` with `for` in this line https://github.com/sccn/roiconnect/blob/e9d9a5f9c8cf14042085b814ad49f5b035ada6c7/pop_roi_connect.m#L281
- I ran your code and it seems that, compared to the working pipeline, the `snips_eps` variable https://github.com/sccn/roiconnect/blob/e9d9a5f9c8cf14042085b814ad49f5b035ada6c7/pop_roi_connect.m#L234 is smaller than 1 in your case. In the working example, it is larger than 1. This variable determines how many trials to use to create a snippet. Let's say you had 2-second epochs and wanted to compute 20-second snippets, it would use 10 trials for it. In your case, you want to compute 20-second snippets but your epoch is already 30 seconds long, which leads to this slightly awkward situation where a single trial would be enough (but this case is not yet covered). When I tried to compute 40-second snippets, this seemed to work. 

My conclusions up to this stage: The desired snippet length has to be longer than the epoch length, we may need to add an error message or split up the epochs as well. If you wanted to stick with having 20-second snippets (or generally, snippets that are shorter than your epochs), you need to create shorter epochs. Our default has been 2 seconds.

Hope that helps, and let me know how it goes!

**Comment by sato16** [comment]
Hi Tien,

Thank you for your kind response and continuous support!

It’s exactly as you said, it seems that the cause was the data length of my data being too long. Both of the following cases worked properly:

1. When the snip_length argument is set to a value larger than the data epoch's length.
`EEG = pop_roi_connect(EEG, 'methods', measures, 'snippet', 'on', 'snip_length', 60, 'fcsave_format', 'mean_snips');`
However, the following warning appears, indicating that using 30 seconds of data might not be the best approach. 
`warning: 30 seconds are thrown away.`
While I have not fully understood it, it seems that the remaining data, which does not have enough of the specified `snip_length` after splitting, is discarded. Therefore, setting a longer snippet length might result in more data being wasted.(Since I would like to handle a variable number of epochs for each subject)

2. Re-epoching every 2 seconds.
This seems to be a better solution. For future users encountering similar issues, I attached the re-epoching script below.
```
EEGorignal =EEG;
%make continuous data and regrepoch as 2 sec data
EEG_continuous = eeg_epoch2continuous(EEG);
EEG_2sec = eeg_regepochs(EEG_continuous, 2, [0 `2]);
EEG = EEG_2sec;
```
After that, the snippets analysis functions properly.

In addition, thank you for guiding me on the basic debugging way for `parfor`.

Once again, I appreciate your help despite your busy schedule!

Best,
Fumiaki

**Comment by sato16** [comment]
Sorry for the multiple postings.

I've noticed that both of the above methods work, but they yield significantly different results. When snip_length is set to 60 seconds, I confirmed that the MIM for each frequency band is almost uniform. 
I have attached the script with the results. You can see that the two scripts use the same data, but the results are different.
[test_30sec_snippet_scripts_with_results.zip](https://github.com/user-attachments/files/16066202/test_30sec_snippet_scripts_with_results.zip)

My understanding was that snippets analysis segments and processes data to align the scale of outputs for comparing different datasets. However, I didn't anticipate such a significant change in the results when altering the snip_length.
I wonder why there is such a significant change in the results like this ?

Is there a recommended way to determine the optimal snip_length setting? For example, should snip_length be chosen based on the number of epochs? Any guidance on this would be greatly appreciated.

Thank you for your help.
Fumiaki

**Comment by nguyen-td** [comment]
Interesting observation, thanks for posting. @stefanhaufe, do you have any suggestions?

**Comment by stefanhaufe** [comment]
I will have a look, yes. But it would be good if we could also arrange a quick call @nguyen-td to clarify what the current implementation is doing.

**Comment by sato16** [comment]
Hi,

I would like to gently check in to see if there’s been any progress on the issue I brought up earlier. I understand you’re likely busy, but if possible, I would greatly appreciate any insights.

Also, given the current situation, do you have any recommendations on the best way to analyze by roiconnect? 
The analysis I would like to perform involves comparing connectivity in long-duration data, where the length varies between subjects, to shuffled data. 
I understand that `conn_stat ` is not yet implemented in snippets analysis. Would it be methodologically correct to calculate `mean_snips` and pass it to `shuffle_BS` for statistical comparison? Alternatively, is there a statistical approach that would allow me to use the snippets of data before averaging? In addition to the `snip_length` issue, I would appreciate it if you could provide guidance on this matter as well.

Thank you so much for your time and help.

Best regards,
Fumiaki

**Comment by nguyen-td** [comment]
Hi Fumiaki,

Thank you for the reminder and apologies for the delayed response. We had a discussion and here are the answers

**Q:** What's the best way to analyze snippets?
**A:** First, you generally want to choose your snippet length to be as long as possible. Say you had two datasets that are 5 mins and 8 mins long, 5 min snippets might be a good choice. 

Second, you want to try to discard as little data as you can. In the above example, 4 min snippets can make sense here because then you would only discard 1 min instead of 3 mins for the second dataset. Of course, you could also pick one minute, then no data would need to be discarded. 

Third, you should avoid going below 1 minute because your noise floor would be too high otherwise. 

**Q:** How to do statistics on snippets?
**A:** There are a few ways to do it. Unfortunately, none of them are implemented yet and I may not have enough time to do it myself in the near future but I add descriptions how I would do it (if/when I have time).

First, you can perform statistics over the mean of the snippets. You would first create surrogates by shuffling the epochs, then you would divide the snippets into epochs (like normally) and then you compute connectivity over snippets. Finally, you would take the mean over the connectivity snippets. This isn't super straightforward to implement in the current architecture yet. We would probably have to define a new function `make_snippets(...)` that implements the snippet functionality, which can be called _within_ the shuffling methods (`shuffle_BS` or `shuffle_CS`). 

Second, you could also shuffle within the snippets, i.e., you would not call `roi_connect(...)`
https://github.com/sccn/roiconnect/blob/7df8313de38c94f6ce0d1b6a2bf821f8204ea2d6/pop_roi_connect.m#L288
but `roi_connstats(...)` like here 
https://github.com/sccn/roiconnect/blob/7df8313de38c94f6ce0d1b6a2bf821f8204ea2d6/pop_roi_connect.m#L377
This might be the more preferred choice because you could potentially better conserve the time dependencies within the snippets, which may give you a better null distribution. With this method, you would end up with p-values for each snippet. You could then perform group statistics (treating the snippets as different groups), e.g., using Stouffer's method (https://github.com/fpellegrini/MotorImag/blob/main/fp_stouffer.m), to aggregate the p-values.

As I mentioned earlier, my time to actively work on this project is quite constraint these days and we are also waiting for a new member to join. In the meantime, feel free to make adjustments yourself, we can always discuss the details together!

**Comment by sato16** [comment]
Hi Tien,

Thank you, as always, for the detailed information!
I understand how to select the snippet length. In my case, since the length of data varies between subjects, ranging from 30 seconds to several minutes, I will first try using a `snip_length` of 60 seconds. If the noise has a significant impact, I will consider trying a longer `snip_length.`

Thank you also for the advice on statistical analysis. I will try implementing it myself, referring to existing scripts such as `fp_stouffer.m` and `roi_connstats.m`.

Should any unclear points arise, I would appreciate your further advice.
I truly appreciate your time and effort, especially given your busy schedule. 
Thank you again for your continued support!

Best,
Fumiaki

**Comment by nguyen-td** [comment]
Sounds good! Good luck and let us know if there are any follow-up questions.
